on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1.0.2
        with:
          auto-update-conda: true
      - name: Install ccache
        run: sudo apt-get install -y ccache
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ steps.current-time.outputs.time }}
          restore-keys: |
            ${{ runner.os }}-ccache-
      - name: Ccache stats
        run: |
          ccache -s
          ccache -z
      - name: Install anaconda-client and conda-build
        shell: bash -l {0}
        run: |
          conda install -y anaconda-client conda-build
      - name: conda-build
        shell: bash -l {0}
        run: conda build -c conda-forge --output-folder . .
      - name: Upload to anaconda
        # if: github.event_name == 'release'
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: anaconda upload --label main linux-64/*.tar.bz2
