on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1.0.2
        with:
          activate-environment: pclpy
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - name: Install ccache
        run: sudo apt-get install -y ccache
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ steps.current-time.outputs.time }}
          restore-keys: |
            ${{ runner.os }}-ccache-
      - name: Show ccache stats
        run: ccache -s
      - name: Clear ccache stats
        run: ccache -z
      - shell: bash -l {0}
        run: pip install -r requirements-dev.txt
      - shell: bash -l {0}
        run: scripts/download_pcl.sh
      - shell: bash -l {0}
        run: scripts/generate_points_and_bindings.sh
      - shell: bash -l {0}
        run: python setup.py build
      - name: Show ccache stats
        run: ccache -s
      - name: Import smoke test
        shell: bash -l {0}
        run: |
          pip install -e .
          python -c 'import pclpy'
